[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "bun run dev"
  port = 5173

[images]
  remote_images = [
    "https://same-assets.com/images/**"
  ]
